### ISSUE TITLE
A user can view recipes within the database.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/SQL-recipe-app#1]
# Motivation
A user can visit the web app and view a list of recipes that are currently within the PostgreSQL database.

# Implementation 
1.  The user opens the app.
2. The user is presented with a landing page that has a list of recipe titles.
3. The user clicks a button located next to the recipe title to expand the information related to that recipe.
4. The app will display the ingredients of the selected recipe, along with instructions/directions on how to make the selected recipe.

# Flow Chart
![capture](https://user-images.githubusercontent.com/14259747/41574201-6565ce92-7335-11e8-90d0-1ab0e851ca54.PNG)

# Wireframe
![layout](https://user-images.githubusercontent.com/14259747/41574203-69485fe8-7335-11e8-9b46-ad43d51192b2.PNG)

# Data model
```
Recipe Title
Recipe Ingredients
Recipe Directions
```

# Component hierarchy
```
<App>
  <Dust>
    <PostgreSQL/>
  </Dust>
</App>
```

# Research
[Dust JS](http://www.dustjs.com/)
[PostgreSQL](https://www.postgresql.org/)
[Bootstrap](https://getbootstrap.com/)
[Express JS](https://expressjs.com/)

# Tasks
**General** 
- [x]  Install Dependancies
- [x]  Create PostgreSQL database
- [x]  Populate PostgreSQL database with recipes
- [x]  Assign Dust engine to .dust files
- [x]  Get Express server up and running 
- [x]  Have Express render our Dust index file
- [x]  Initalize Bootstrap
- [x]  Fetch recipe data from PostgreSQL
- [x]  Display recipe data using Dust
- [x]  Style using Bootstrap
- [x]  (more to come!...?)
