### ISSUE TITLE
A user can add a recipe to the database.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/SQL-recipe-app#2]
# Motivation
A user can visit the web app and add a recipe to the database.

# Implementation 
1.  The user opens the app.
2. The user is presented with a landing page that has a list of recipe titles and an "Add Recipe" button at the top of the list. 
3. The user can click the "Add Recipe" button which will, in turn, open a modal with the following text fields:
Recipe Name, Ingredients, Directions.
4. After the user has finished filling out the corresponding text fields, the user can choose to save their addition or close the modal.
5. Upon saving the new recipe, the app will generate a new item in the list of recipes that contain the users' new addition. 

# Flow Chart
Click to enlarge
![capture](https://user-images.githubusercontent.com/14259747/41587540-50b13b92-7364-11e8-9baf-5ec293f9396f.PNG)

# Wireframe
![wireframe](https://user-images.githubusercontent.com/14259747/41587553-585dd5bc-7364-11e8-8924-ccdbe6289de5.PNG)

# Data model
```
Recipe Title
Recipe Ingredients
Recipe Directions
```

# Component hierarchy
```
<App>
  <Dust>
    <PostgreSQL/>
  </Dust>
</App>
```

# Research
[Dust JS](http://www.dustjs.com/)
[PostgreSQL](https://www.postgresql.org/)
[Bootstrap](https://getbootstrap.com/)
[Express JS](https://expressjs.com/)

# Tasks
**General** 
- [x]  Create button at top of the landing page
- [x]  Have button trigger a pop-up modal
- [x]  Populate modal with a form that has three fields - Recipe Name - Ingredients - Directions
- [x]  Create two buttons that can close the modal, or submit the text that was input into the form
- [x]  Enable submit button to make post request that inserts text into recipes database
- [x]  Redirect page back to the landing page for refresh
- [x]  (more to come!...?)
