### ISSUE TITLE
A user can edit a recipe within the database.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/SQL-recipe-app#3]
# Motivation
A user can visit the web app and edit or delete recipes that they wish to alter.

# Implementation 
1.  The user opens the app.
2. The user is presented with a landing page that has a list of recipe titles that can be expanded for more details.
3. After expanding a recipe the user can click on a button to edit the contents of a recipe.
4. After the button has been pressed the user is prompted with a modal containing the current information being stored for that recipe, and two buttons; one for discarding changes and another for saving changes. 
5. After saving changes the home page is updated and refreshed with the new recipe added to the list

# Flow Chart
![1](https://user-images.githubusercontent.com/14259747/41705309-77df9652-74ed-11e8-930e-fdba3f8c0008.PNG)

# Wireframe
![2](https://user-images.githubusercontent.com/14259747/41705311-79559fc2-74ed-11e8-9b5d-7c541854a6d1.PNG)
After clicking edit button...
![3](https://user-images.githubusercontent.com/14259747/41705317-7e1c5d3e-74ed-11e8-80f6-cd213f5e2a6f.PNG)

# Data model
```
Recipe Title
Recipe Ingredients
Recipe Directions
```

# Component hierarchy
```
<App>
  <Dust>
    <PostgreSQL/>
  </Dust>
</App>
```

# Research
[Dust JS](http://www.dustjs.com/)
[PostgreSQL](https://www.postgresql.org/)
[Bootstrap](https://getbootstrap.com/)
[Express JS](https://expressjs.com/)

# Tasks
**General** 
- [x]  Create the edit button
- [x]  Link the edit button to new modal
- [x]  Create a form in edit modal for submitting post requests to "edit"
- [x]  Have the new edit modal grab current values using jquery
- [x]  Have the save button in new modal submit post request to "edit"
- [x]  Have post request send an update request to PostgreSQL server
- [x]  Have post request redirect back to "/"
- [x]  Style accordingly
- [x]  (more to come!...?)
