### ISSUE TITLE
A user can delete a recipe.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/SQL-recipe-app#7]
# Motivation
A user can visit the web app and delete a recipe that is already in the recipe list.

# Implementation 
The user opens the web app & is presented with a recipe that they regret logging
The user expands the regretable recipe details 
The user clicks the delete button & accepts the confirmation of deleting the selected recipe
The app sends an express delete request, along with a delete query to the database
The app sends the "A-OK" status code (200)
The list of recipes is updated and no longer contains the offending recipe

# Flow Chart
![deletewire](https://user-images.githubusercontent.com/14259747/41705378-a90df70a-74ed-11e8-82a9-00b8a3558f40.PNG)

# Wireframe
![delete](https://user-images.githubusercontent.com/14259747/41705368-a3f54d9a-74ed-11e8-8df3-dcb14ac14daa.PNG)

# Data model
```
Recipe Title
Recipe Ingredients
Recipe Directions
```

# Component hierarchy
```
<App>
  <Dust>
    <PostgreSQL/>
  </Dust>
</App>
```

# Research
[Dust JS](http://www.dustjs.com/)
[PostgreSQL](https://www.postgresql.org/)
[Bootstrap](https://getbootstrap.com/)
[Express JS](https://expressjs.com/)

# Tasks
**General**
- [x]  Create a delete button within the details of each recipe that is generated
- [x]  Link the delete button to a delete recipe class & have it grab the ID of the recipe it belongs to
- [x]  Store the ID of the deleted recipe
- [x]  Upon clicking the delete button have a confirmation box appear to make sure that deleting the recipe is what the user intended
- [x]  Upon pushing the confirmation button, redirect the user to the '/' home page
- [x]  Create an Express app.delete method that grabs the id of the deleted recipe
- [x]  WIthin the app.delete method submit a delete query to the database along with the ID of the recipe to be deleted
- [x]  Send status code 200 upon completion
- [x]  (more to come!...?)
